# Deploy NodeJS project to GitHub Pages
name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22 # current LTS

      - name: Install node packages
        run: npm i

      - name: Setup env var(s)
        run: |
          # TODO: Refactor conditional to be more robust
          if [[ "${{ github.event.repository.name }}" =~ ^.*\.github\.io$ ]]; then
            # Leave blank for GitHub Pages base URI path
            echo "BASE_PATH=" >> $GITHUB_ENV
          else
            # Otherwise, prepend repository name
            echo "BASE_PATH=/${{ github.event.repository.name }}" >> $GITHUB_ENV
          fi

      - name: Build website
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build # entire build is within this directory
          retention-days: 7 # retain artifact for a week, for debugging
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
